#!/usr/bin/env python

#Copyright (c) 2017 Andre Santos
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.

import socket
from time import sleep

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((socket.gethostname(), 8421))
    try:
        print "Sending topic name."
        sock.sendall("talker")
        ack = sock.recv(4096)
        if ack != "OK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending random trash."
        sock.sendall("random trash")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending partial trash."
        sock.sendall("0.2 trash")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending out of bounds values."
        sock.sendall("1 0")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending proper values."
        sleep(0.5)
        while True:
            sock.sendall("0.25 1.5708")
            ack = sock.recv(4096)
            if ack != "OK":
                print ">> Protocol error. Received:", ack
                return
            sleep(0.5)
    finally:
        sock.close()

if __name__ == "__main__":
    main()
