#!/usr/bin/env python

import socket
from time import sleep

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((socket.gethostname(), 8421))
    try:
        print "Sending topic name."
        sock.sendall("talker")
        ack = sock.recv(4096)
        if ack != "OK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending random trash."
        sock.sendall("random trash")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending partial trash."
        sock.sendall("0.2 trash")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending out of bounds values."
        sock.sendall("1 0")
        ack = sock.recv(4096)
        if ack != "NOK":
            print ">> Protocol error. Received:", ack
            return
        print "  > OK"

        print "Sending proper values."
        sleep(0.5)
        while True:
            sock.sendall("0.25 1.5708")
            ack = sock.recv(4096)
            if ack != "OK":
                print ">> Protocol error. Received:", ack
                return
            sleep(0.5)
    finally:
        sock.close()

if __name__ == "__main__":
    main()
